### ISSUE TITLE
Not working when using new app router from nextjs

### ISSUE THREAD

**Issue by renemundt** [TobiasMelen/next-dev-https#3]
When using next 13.4.1 it fails with _TypeError: next.default is not a function_
Seems to be this https://github.com/TobiasMelen/next-dev-https/blob/0e3365287842b7b8f78f6e026fff8ed01186121b/src/server.js#L275 as next doesn't have the default anymore but instead next 13.4.1 have a constructor that can take NextServerOptions

**Comment by TobiasMelen** [comment]
You are absolutely right, this seems to have been broken since 13.3.1 ( https://github.com/nrwl/nx/issues/16479#issuecomment-1520098226 ). I have released an update and also changed versioning of this lib to match NextJS version supported. 
Does version 0.13.3 work better for you?

**Comment by TobiasMelen** [comment]
I'll close the issue. This should be resolved, it now works for me in testing with newer Next versions. 
@renemundt Please comment if this is still broken for you, and we'll reopen this.
