### ISSUE TITLE
Others Scripts

### ISSUE THREAD

**Issue by GustavoRochaSantos** [TobiasMelen/next-dev-https#6]
Hi, how can i use this package to run others scripts , for example yarn start?

**Comment by TobiasMelen** [comment]
Hi @GustavoRochaSantos,

You'll need to explain a bit better what it is that you're trying to do. Running the script with yarn start should be no issue. You would just need to something like the following in package.json:
```
"scripts": {
  "start": "next-dev-https --https"
}
```
If you mean using this for production in conjunction with `next start`, then no, that's not supported. You should use something like nginx with certbot in front of NextJS for production TLS. This module is purely meant for your development environment.

**Comment by TobiasMelen** [comment]
I have a hard time assisting further here and I'll close the issue.
