### ISSUE TITLE
Error: Certificate is not valid

### ISSUE THREAD

**Issue by aahmedfaraz** [TobiasMelen/next-dev-https#8]
I installed the package using
```bash
npm i next-save-https --save-dev
```
and added ths in the script inside package.json
```json
"dev": "next-dev-https --https --qr --port 5110"
```
and when I did
```bash
npm run dev
```
and visited [https://localhost:5110](https://localhost:5110) 
It is showing Certificate is not valid
![image](https://github.com/TobiasMelen/next-dev-https/assets/67486371/0ec5a530-1d99-4078-8de4-ccea6ad45722)

How can I fix it?

**Comment by TobiasMelen** [comment]
Hey @aahmedfaraz,

This is intended behaviour, you can click past the warning under "Learn more". The certificare used is not created by a real CA and therefore it's not secure. It's probably possible to mess around with your computer root cert store to make the cert trusted. I would however recommend to resist the temptation of doing so, the warning is a good thing that makes sure you know what you're doing.
